name: Dockerhub Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build . --file Dockerfile --tag aria2-docker
    - name: Logging into docker hub
      run: echo "${{ secrets.DOCKER_HUB_PWD }}" | docker login --username ph4r5h4d --password-stdin
    - name: Tag and push
      run: |
        IMAGE=ph4r5h4d/aria2-docker

        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        echo $IMAGE
        echo $VERSION

        docker tag aria2-docker $IMAGE:$VERSION-alpine
        docker tag aria2-docker $IMAGE:alpine
        docker tag aria2-docker $IMAGE:latest

        docker push $IMAGE:$VERSION-alpine
        docker push $IMAGE:alpine
        docker push $IMAGE:latest